---
Name: nswdpc-cache-headers-middleware
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Control\Middleware\HTTPCacheControlMiddleware:
    class: NSWDPC\Utilities\Cache\CacheHeaderProxyMiddleware
---
Name: nswdpc-cache-headers-statemodification
---
SilverStripe\Control\Controller:
  extensions:
    - 'NSWDPC\Utilities\Cache\CacheStateModificationExtension'
---
Name: nswdpc-cache-headers-contentcontroller
---
SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - 'NSWDPC\Utilities\Cache\ContentControllerExtension'
---
Name: nswdpc-cache-headers
---
NSWDPC\Utilities\Cache\CacheHeaderConfiguration:
  # one of the HTTPCacheControlMiddleware STATE_* constants
  state: 'enabled'
  max_age: null
  s_max_age: null
  vary : null
  no_store: null
  must_revalidate: null
  no_cache: null
  # controller configuration
  controllers:
    disableCache:
      - 'SilverStripe\Dev\DevelopmentAdmin'
      - 'SilverStripe\Dev\DevBuildController'
      - 'SilverStripe\Dev\DevConfigController'
      - 'SilverStripe\Dev\SapphireInfo'
      - 'SilverStripe\Dev\InstallerTest'
      - 'SilverStripe\GraphQL\Controller'
      - 'SilverStripe\ORM\DatabaseAdmin'
      - 'SilverStripe\Security\Security'
      - 'SilverStripe\ShareDraftContent\Controllers\ShareDraftController'
      - 'SilverStripe\Assets\Storage\ProtectedFileController'
