---
Name: nswdpc-cache-headers-middleware
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Control\Middleware\HTTPCacheControlMiddleware:
    class: NSWDPC\Utilities\Cache\CacheHeaderProxyMiddleware
---
Name: nswdpc-cache-headers
---
NSWDPC\Utilities\Cache\CacheHeaderConfiguration:
  # one of the HTTPCacheControlMiddleware STATE_* constants
  state: 'enabled'
  max_age: null
  s_max_age: null
  vary : null
  no_store: null
  must_revalidate: null
  no_cache: null
